version: '3.3'

services:
  database:
    image: mysql
    #command: --default-authentication-plugin = mysql_native_password
    #command: --init-file /data/application/init.sql
    volumes:
      - ./database/shortdump.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: playground-web-backend
      MYSQL_USER: playground-web-backend
      MYSQL_PASSWORD: playground-web-backend
    ports:
      - 3306:3306

  front-end:
    image: playground-web-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://playground-web-backend:8080/
    ports:
      - 3000:3000

  back-end:
    image: playground-web-backend
      MYSQL_URL: jdbc:mysql//database:3306/2002T4
    ports:
      - 8080:8080
